In [2]:
# 导入numpy包
import numpy as np

## 简单入门：

In [3]:
data1 = [2, 3, 4] # 列表
arr1 = np.array(data1)
arr1

array([2, 3, 4])

In [4]:
data2 = (5, 6, 7)  # 元祖
arr2 = np.array(data2)
arr2

array([5, 6, 7])

In [5]:
data3 = ([1, 2, 3, 4], [5, 6, 7, 8])  # 多维数组，2个列表
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr3.shape  # 查看数据格式，2行4列

(2, 4)

In [7]:
arr3.dtype  # 查看数据类型，是整型

dtype('int32')

In [8]:
data4 = [1.2, 2, 3.34, 5]
arr4 = np.array(data4)
arr4

array([1.2 , 2.  , 3.34, 5.  ])

In [9]:
arr4.dtype # 查看数据类型，是浮点型

dtype('float64')

## 创建数组
|函数	|使用说明|
| :--------| :------------|
|arange	|类似于内置的range函数，用于创建数组|
|ones	|创建指定长度或形状的全1数组|
|ones_like	|以另一个数组为参考，根据其形状和dtype创建全1数组|
|zeros、zeros_like	|类似于ones、ones_like，创建全0数据|
|empty、empty_like	|同上，创建没有具体值的数|
|eye、identity	|创建正方的N*N单位矩阵\

## ndarray数据对象属性
|函数	|使用说明|
| :---| :---|
|.ndim	|秩，即数据轴的个数|
|.shape	|数组的维度|
|.size	|元素的总个数|
|.dtype	|数据类型|
|.itemsize	|数组中每个元素的字节大小|

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.empty(2)

array([0., 0.])

In [16]:
np.empty((2, 2, 3))

array([[[9.49897879e-312, 2.47032823e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.04082753e-047]],

       [[5.00419969e-090, 5.99520921e-066, 2.83103912e-033],
        [2.52701053e-052, 3.99910963e+252, 5.82471487e+257]]])

In [17]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr5 = np.empty_like(arr3)
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
arr5.dtype

dtype('int32')

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [21]:
data = ([2, 3, 4],[5, 3, 2])
arr = np.array(data)
arr

array([[2, 3, 4],
       [5, 3, 2]])

In [22]:
arr.ndim # 2维数组

2

In [23]:
arr.shape # 2行3列

(2, 3)

In [24]:
arr.size # 6个数字

6

arr数据的数据类型是int32位，对于计算机而言，1个字节是8位，所以arr的itemsize属性值为4

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr.itemsize

4

In [27]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr2 = np.arange(5, dtype='float64')
arr2

array([0., 1., 2., 3., 4.])

In [30]:
arr2.dtype

dtype('float64')

In [31]:
arr2 = arr2.astype('int')
# arr2 = arr2.astype(np.int32)
arr2

array([0, 1, 2, 3, 4])

In [32]:
arr2 = arr2.astype(np.float64)
arr2

array([0., 1., 2., 3., 4.])

In [33]:
arr1

array([0, 1, 2, 3, 4])

In [34]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [35]:
arr3.astype(np.int32)

array([0, 1, 2, 3, 4])

In [36]:
arr = np.array([2.3, 3.5, 6.9, 10.0])
arr

array([ 2.3,  3.5,  6.9, 10. ])

In [37]:
arr.astype('int32')

array([ 2,  3,  6, 10])

In [38]:
arr  # 原数组并不改变，需要赋值给新数组

array([ 2.3,  3.5,  6.9, 10. ])

## 数据变换
- 数据重塑
	对于定义好的数组，可以通过reshape方法改变其数据维度。传入的参数为新维度元祖。

In [39]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
arr.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
# 多维数组也可以被重塑
arr = np.array([[3, 4, 5], [1, 2, 3]])
arr.reshape((3,2))

array([[3, 4],
       [5, 1],
       [2, 3]])

In [42]:
# reshape的参数中的一维参数可以设置为-1，
# 表示数据的维度可以通过数据本身来推断
arr = np.arange(12)
arr.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 与reshape相反的方法是数据散开（revel）或扁平化（flatten）：

In [43]:
arr = np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
arr.ravel()
# arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr  # 数据重塑不会改变原数组

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 数据合并
- 数据合并用于几个数组间的操作，concatenate方法通过指定轴方向，将多个数组合并在一起：

In [46]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr2 = np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
np.concatenate([arr1, arr2], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
np.concatenate([arr1, arr2], axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

- 此外，NumPy中还提供了几个比较简单易懂的方法，如vstack和hstack：

In [50]:
np.vstack((arr1, arr2)) # 垂直叠

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
np.hstack((arr1, arr2)) # 水平叠

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## 数组拆分
- 通过split方法可以将数组拆分为多个数组：

In [52]:
arr = np.arange(12).reshape((6,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
np.split(arr, [2, 4])

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11]])]

## 数据转置和轴对称
- 转置是数组重塑的一种特殊形式，可以通过transpose方法进行转置（X轴变成Y轴，Y轴变成X轴）。
- transpose方法需要传入轴编号组成的元祖，也可以使用.T：

In [54]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## NumPy的随机数函数
|函数	|使用说明|
|--|--|
|rand	|产生均匀分布的样本值|
|randint	|给定范围内取随机整数|
|randn	|产生正态分布的样本值|
|seed	|随机数种子|
|permutation	|对一个序列随机排序，不改变原数组|
|shuffle	|对一个序列随机排序，改变原数组|
|uniform(low, high, size)	|产生具有均匀分布的数组，low表示起始值，high表示结束值，size表示形状|
|normal(loc, scale, size)	|产生具有正态分布的数组，loc表示均值，scale表示标准差|
|poisson(lam, size)	|产生具有泊松分布的数组，lam表示随机事件发生率|

In [57]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[140, 171, 103, 197],
       [175, 149, 182, 187],
       [123, 197, 197, 199],
       [161, 151, 134, 174],
       [186, 151, 168, 157]])

In [58]:
arr = np.random.randn(2, 3, 4)
arr

array([[[ 0.7921049 ,  1.32498524,  2.10867043, -1.22066785],
        [ 1.02991882, -1.43337976,  0.13726194,  1.32193808],
        [-0.97569253,  1.24247297,  1.43386248,  0.55386188]],

       [[-0.18779211, -1.0110677 ,  0.96992206, -1.57827922],
        [-0.06352645, -1.19669311,  1.30496412, -1.18046166],
        [-1.13298292, -1.69096778,  1.7953144 ,  1.91829738]]])

In [59]:
arr = np.random.normal(4, 5 ,size=(3,5))
arr

array([[ 0.9473065 ,  1.66984085,  8.0978842 ,  4.34207184, 11.01268447],
       [ 0.33755379, 13.95040307,  1.2039431 , -1.34059758, -1.9734646 ],
       [12.72421404,  0.83157868,  2.67466625,  3.01508154,  6.53101389]])

In [60]:
arr = np.random.seed(5)
print(arr)

None


In [61]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[199, 178, 161, 116],
       [173, 108, 162, 127],
       [130, 180, 107, 176],
       [115, 153, 180, 127],
       [144, 177, 175, 165]])

In [62]:
np.random.permutation(arr)

array([[115, 153, 180, 127],
       [199, 178, 161, 116],
       [173, 108, 162, 127],
       [130, 180, 107, 176],
       [144, 177, 175, 165]])

In [63]:
np.random.shuffle(arr)
arr

array([[199, 178, 161, 116],
       [115, 153, 180, 127],
       [130, 180, 107, 176],
       [144, 177, 175, 165],
       [173, 108, 162, 127]])

## 数组的索引和切片
- 索引<br/>
    一维数组的索引类似Python列表：

In [64]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[3]

3

In [66]:
arr[-1]

9

In [67]:
arr[2] = 123
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [68]:
arr[3] = 99
arr

array([  0,   1, 123,  99,   4,   5,   6,   7,   8,   9])

In [69]:
arr1 = arr[-3:-1]
arr1

array([7, 8])

In [70]:
arr1[:] = 77
arr

array([  0,   1, 123,  99,   4,   5,   6,  77,  77,   9])

In [71]:
arr

array([  0,   1, 123,  99,   4,   5,   6,  77,  77,   9])

- 数组的切片和索引返回都是原始数组的视图。在视图上的操作都会使原数组发生改变。
- 如果需要赋值数据，则可以同copy方法：


In [28]:
arr1 = arr[1].copy()
arr1 = 34
arr

array([  0,   1, 123,  99,   4,   5,   6,  77,  77,   9])

- 二维数组的索引

In [29]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
arr[0]

array([0, 1, 2, 3, 4])

In [31]:
arr[2]

array([10, 11, 12, 13, 14])

In [32]:
arr[0][3]

3

In [33]:
arr[2, 3] # 两种方法等价

13

- 高维数组的索引

In [34]:
arr = np.arange(12).reshape(2, 2, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
arr[1, 1]

array([ 9, 10, 11])

In [37]:
arr[0, 1, 2]

5

In [38]:
old = arr[0].copy()
arr[0] = 12
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [39]:
arr[0] = old
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## 切片
- 一维数组的切片类似Python列表：

In [40]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[2:5] # 不包括尾数

array([2, 3, 4])

- 多维数组的切片是按照轴方向进行的，当在中括号中输入一个参数时，数组就会按照0轴（也就是第一轴）方向进行切片：

In [42]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
arr[:, 1]

array([ 1,  4,  7, 10])

In [45]:
arr[:, 1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [46]:
arr[2:, 1:]

array([[ 7,  8],
       [10, 11]])

## 布尔索引
- 如果每个水果对应于datas数组中的每一行，我们要取出‘pear’对应的datas的行，这时就需要用到布尔选择器：

In [47]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
datas = np.random.randint(-1, 1, size=(7,5))

In [48]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [49]:
datas

array([[-1,  0,  0,  0, -1],
       [ 0,  0,  0, -1, -1],
       [ 0, -1, -1,  0,  0],
       [ 0, -1,  0,  0,  0],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1],
       [-1, -1,  0,  0, -1]])

In [51]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])

In [52]:
fruits == 'pear'

array([False, False,  True, False,  True, False,  True])

In [53]:
datas[fruits == 'pear'] # 把是True部位的输出

array([[ 0, -1, -1,  0,  0],
       [ 0, -1,  0,  0,  0],
       [-1, -1,  0,  0, -1]])

In [54]:
datas[fruits != 'pear']

array([[-1,  0,  0,  0, -1],
       [ 0,  0,  0, -1, -1],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1]])

In [55]:
datas[(fruits == 'apple') | (fruits == 'banana')]

array([[-1,  0,  0,  0, -1],
       [ 0,  0,  0, -1, -1],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1]])

- 可以结合切片和索引来使用：

In [56]:
datas[fruits == 'pear', 2:]

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, -1]])

In [57]:
datas[fruits == 'pear', 2]

array([-1,  0,  0])

- 通过以下代码可以完成datas数组中的0值替换为1值：

In [58]:
datas[datas == 0] = 1
datas

array([[-1,  1,  1,  1, -1],
       [ 1,  1,  1, -1, -1],
       [ 1, -1, -1,  1,  1],
       [ 1, -1,  1,  1,  1],
       [ 1, -1,  1,  1,  1],
       [ 1,  1,  1, -1, -1],
       [-1, -1,  1,  1, -1]])

## 花式索引
- 它可以通过整数列表或数组进行索引：

In [59]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
arr[[1, 3, 2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [62]:
arr[[3, 2]]

array([[ 9, 10, 11],
       [ 6,  7,  8]])

In [63]:
arr[[3, 2]][:, [2, 1]]

array([[11, 10],
       [ 8,  7]])

In [64]:
arr[np.ix_([3, 2],[2, 1])]

array([[11, 10],
       [ 8,  7]])

In [66]:
arr = np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

## 数组运算
- 加减乘除

In [67]:
arr + 2

array([[2, 3],
       [4, 5]])

In [68]:
arr - 3

array([[-3, -2],
       [-1,  0]])

In [69]:
arr * 10

array([[ 0, 10],
       [20, 30]])

In [70]:
arr / 2

array([[0. , 0.5],
       [1. , 1.5]])

In [71]:
arr * arr

array([[0, 1],
       [4, 9]])

In [72]:
arr - arr

array([[0, 0],
       [0, 0]])

## 通用函数
- abs函数求绝对值，square求平方：

In [75]:
arr = np.random.randint(-10, 10, size=(3,3))
arr

array([[  2,   2,  -5],
       [  4,   5,   8],
       [-10,  -3,  -3]])

In [76]:
np.abs(arr)

array([[ 2,  2,  5],
       [ 4,  5,  8],
       [10,  3,  3]])

In [77]:
np.square(arr)

array([[  4,   4,  25],
       [ 16,  25,  64],
       [100,   9,   9]], dtype=int32)

- 以上函数都是传入一个数组，所以这些函数都是一元函数。有一些函数需要传入两个数组并返回一个数组，这些函数被称为二元函数，如add函数，minimum函数：

In [78]:
arr1 = np.random.randint(1, 10, size=(5))
arr1

array([7, 1, 1, 9, 6])

In [81]:
arr2 = np.random.randint(1, 10, size=5)
arr2

array([5, 2, 9, 1, 3])

In [82]:
np.add(arr1, arr2)

array([12,  3, 10, 10,  9])

In [83]:
np.minimum(arr1, arr2) # 计算元素最小值

array([5, 1, 1, 1, 3])

- 有些通用函数还可以返回两个数组，如modf函数，可以返回数组元素的小数和整数部分：

In [85]:
arr = np.random.normal(2, 4, size=6)
arr

array([-0.89013059,  7.50036414, -0.98591028,  0.60808341,  7.55095328,
       -1.94174701])

In [86]:
np.modf(arr)

(array([-0.89013059,  0.50036414, -0.98591028,  0.60808341,  0.55095328,
        -0.94174701]), array([-0.,  7., -0.,  0.,  7., -1.]))

- 条件逻辑运算

In [87]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
cond = np.array([True, False, False, True])

- 如果需要通过cond的值来选取arr1和arr2的值，当cond为Ture时，选择arr1的值，否则选择arr2的值，那么可以通过if语句判断来实现：

In [88]:
result = [(x if c else y) for x, y, c in zip(arr1, arr2, cond)]
result

[1, 6, 7, 4]

- 但这种方法存在两个问题：<br/>第一，对大规模数组处理速度不是很快；<br/>第二，无法用于多维数组。若使用Numpy的where函数则可以解决：

In [89]:
result = np.where(cond, arr1, arr2) # cond为条件
result

array([1, 6, 7, 4])

- where函数中的第二个和第三个参数可以为标量。例如：新建一个随机符合正态分布的数组，通过数据处理将正值替换为1，负值替换为-1：

In [90]:
arr = np.random.randn(4, 4)
arr

array([[-0.2613439 ,  1.41883087,  0.01114893,  0.48987958],
       [-0.67046296, -0.02086968,  0.8129733 , -0.80579606],
       [ 1.3591304 ,  0.69865666,  0.0328329 ,  0.1780416 ],
       [-1.50945999,  0.03404126,  1.42094967,  0.37335629]])

In [91]:
new_arr = np.where(arr > 0, 1, -1)
new_arr

array([[-1,  1,  1,  1],
       [-1, -1,  1, -1],
       [ 1,  1,  1,  1],
       [-1,  1,  1,  1]])

- 在if中使用elif函数可以进行多条件判断。np.where函数通过嵌套的where表达式也可以完成同样的功能：

In [92]:
arr = np.random.randint(1, 300, size=(3,3))
arr

array([[258, 179,  87],
       [ 20,  55, 193],
       [ 78,  74, 266]])

In [93]:
new_arr = np.where(arr > 200, 3,
                   np.where(arr > 100, 2, 1))
new_arr

array([[3, 2, 1],
       [1, 1, 2],
       [1, 1, 3]])

In [94]:
arr

array([[258, 179,  87],
       [ 20,  55, 193],
       [ 78,  74, 266]])

## 统计运算
|方法|使用说明|
|--|--|
|sum|求和|
|mean|算术平均数|
|std、var|标准差和方差|
|min、max|最小值和最大值|
|argmin、argmax|最小和最大元素的索引|
|cumsum|所有元素的累积和|
|cumprod|所有元素的累计积|

In [95]:
arr = np.random.randn(4, 4)
arr

array([[-0.6711349 ,  0.38970578,  0.26486549, -0.94990569],
       [ 0.61077637, -1.50885904, -0.63975004, -1.94854334],
       [-1.35663927,  1.24181545,  0.38806226,  1.04083092],
       [-0.48857559, -1.23056871,  2.02032342,  0.27085958]])

In [96]:
arr.sum()

-2.566737321653425

In [97]:
arr.mean()

-0.16042108260333907

In [98]:
arr.std()

1.0765508349704507

- 上面的函数也可以传入axis参数，用于计算指定轴方向的统计值：

In [99]:
arr

array([[-0.6711349 ,  0.38970578,  0.26486549, -0.94990569],
       [ 0.61077637, -1.50885904, -0.63975004, -1.94854334],
       [-1.35663927,  1.24181545,  0.38806226,  1.04083092],
       [-0.48857559, -1.23056871,  2.02032342,  0.27085958]])

In [100]:
arr.mean(axis=1) # x轴，行

array([-0.24161733, -0.87159401,  0.32851734,  0.14300968])

In [101]:
arr.sum(0)  # y轴，列

array([-1.9055734 , -1.10790653,  2.03350113, -1.58675852])

In [102]:
-0.6711349+0.61077637-1.35663927-0.48857559

-1.90557339

In [103]:
-0.6711349+0.38970578+0.26486549-0.94990569

-0.9664693200000001

In [106]:
0.61077637-1.35663927-0.6711349-0.48857559

-1.90557339

- cumsum和cumprod方法会产生计算结果组成的数组：

In [107]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
arr.cumsum(0)  # y轴

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [109]:
arr.cumprod(1) # x轴

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

## 布尔数组运算
- 对于布尔型数组，会强制转换为1和0：

In [112]:
arr = np.random.randn(20)
arr

array([ 0.95892656, -0.82765618, -0.57185239,  0.28532125, -0.28890779,
       -0.73697211,  0.48577995,  0.33081322, -0.24758143,  0.26605763,
       -1.79854937,  1.02050702, -0.20205117, -0.18048743,  0.34275531,
        0.16210142, -0.7000911 ,  1.43785723,  0.18381712,  0.94266896])

In [113]:
(arr > 0).sum()

11

- 还有两个方法any和all也可以用于布尔型数组运算。any方法用于测试数组中是否存在一个或多个True；all方法用于检查数组中的所有值是否为True：

In [114]:
arr = np.array([True, False, False, True])
arr

array([ True, False, False,  True])

In [115]:
arr.any()

True

In [116]:
arr.all()

False

In [117]:
arr = np.random.randn(10)
arr

array([ 0.37659929, -0.63194014, -0.56306709, -1.19629992, -1.20571704,
       -0.26108442, -0.98473888,  0.07162353,  0.97184838,  0.69552997])

In [118]:
arr.sort()   # 由小到大
arr

array([-1.20571704, -1.19629992, -0.98473888, -0.63194014, -0.56306709,
       -0.26108442,  0.07162353,  0.37659929,  0.69552997,  0.97184838])

In [119]:
arr = np.random.randn(5, 3)
arr

array([[ 0.43162822,  0.7663635 ,  0.21960445],
       [ 0.33262602, -0.14541558,  0.08921563],
       [-0.28611902, -0.51654573, -2.01979269],
       [-0.23886778, -0.65476862,  1.74028736],
       [-0.11107771,  1.19957572,  0.39725042]])

In [120]:
arr.sort(1) # x轴上的数字
arr

array([[ 0.21960445,  0.43162822,  0.7663635 ],
       [-0.14541558,  0.08921563,  0.33262602],
       [-2.01979269, -0.51654573, -0.28611902],
       [-0.65476862, -0.23886778,  1.74028736],
       [-0.11107771,  0.39725042,  1.19957572]])

## 集合运算
- 常使用np.unique方法找出唯一值：

|方法	|使用说明|
|--|--|
|unique(x)|	唯一值|
|intersect1d(x, y)	|公共元素|
|union1d(x, y)	|并集|
|in1d(x, y)|	x的元素是否在y中，返回布尔型数组|
|setdiff1d(x, y)|	集合的差|
|setxor1d(x, y)|	交集取反|

In [121]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [122]:
np.unique(fruits)

array(['apple', 'banana', 'pear'], dtype='<U6')

In [125]:
arr = np.array([2, 3, 3, 4, 1, 2])
arr

array([2, 3, 3, 4, 1, 2])

In [126]:
np.unique(arr)  # PS：对唯一值进行了排序

array([1, 2, 3, 4])

- np.in1d方法用于测试几个数组中是否包含相同的值，返回一个布尔值数组

In [127]:
arr = np.array([2, 3, 5, 7])
arr

array([2, 3, 5, 7])

In [130]:
np.in1d(arr, [2,7]) # 此处是数字1

array([ True, False, False,  True])

## 线性代数
- 矩阵点积dot函数：

In [131]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr2 = np.arange(9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
np.dot(arr1, arr2)

array([[24, 30, 36],
       [51, 66, 81]])

- 矩阵行列式：

In [134]:
from numpy.linalg import det

In [135]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [136]:
det(arr)

-2.0000000000000004

## 数据的存储
- 通过np.savetxt方法可以对数组进行存储：

In [137]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [138]:
np.savetxt('ch2ex1.csv', arr, fmt='%d', delimiter=',')

In [139]:
!type ch2ex1.csv

0,1,2
3,4,5
6,7,8
9,10,11


## 数据的读取
- 对于存储的文件，可以通过np.loadtxt方法进行读取，并将其加载到一个数组中：

In [140]:
arr = np.loadtxt('ch2ex1.csv', delimiter=',')
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

## 案例：图像反色

In [74]:
from PIL import Image
import numpy as py

In [75]:
im = np.array(Image.open('./数据/1.jpeg'))
print(im.shape, im.dtype)

(350, 583, 3) uint8


In [76]:
im

array([[[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [195, 195, 195]],

       ...,

       [[210, 210, 210],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [122, 122, 122],
        [124, 124, 124],
        [125, 125, 125]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [120, 120, 120],
        [122, 122, 122],
        [124, 124, 124]],

       [[211, 211, 211],
        [211, 211, 211],
        [212, 212, 212],
        ...,
        [119, 119, 119],
        [121, 121, 121],
        [123, 123, 123]]

In [77]:
b = [255, 255, 255] - im  # 数组运算
new_im = Image.fromarray(b.astype('uint8'))
new_im.save('./testdata/new_1.jpg')  # 保存为新图像